#!/usr/bin/env bash
# Install the load balancer

sudo apt-get update
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
	bind :80
	mode http
	option httpclose
	option forwardfor
	balance roundrobin
	server 150416-web-01 52.87.254.214 check
	server 150416-web-02 100.25.156.168 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart
