#!/usr/bin/env bash
# What's keeping your Ubuntu container's Nginx installation from listening on port 80
# Configure nginx to run and listen to port 80.

rm /etc/nginx/sites-enabled/default
In -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
