#!/usr/bin/env bash
# Configures a server to listen on port 80 of all server's IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
