#!/usr/bin/env bash
# Configures a server to listen on port 80 of all server's IPs
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
